# Generated by Django 5.2 on 2025-04-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Patente"
                    ),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="Marca")),
                ("model", models.CharField(max_length=50, verbose_name="Modelo")),
                ("year", models.PositiveIntegerField(verbose_name="Año")),
                (
                    "owner_name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del propietario"
                    ),
                ),
                (
                    "owner_phone",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del propietario"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RepairRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha de reparación")),
                (
                    "description",
                    models.TextField(verbose_name="Descripción de la reparación"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repairs",
                        to="workshop.vehicle",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
        ),
    ]
